CREATE TABLE EMPLOYE (
NUEMPL NUMBER(4,0) PRIMARY KEY,
NOMEMPL VARCHAR2(20) NOT NULL,
HEBDO NUMBER(2,0) check(hebdo<=35),
AFFECT NUMBER(2,0) NOT NULL
);

CREATE TABLE PROJET (
NUPROJ NUMBER(3,0) PRIMARY KEY,
NOMPROJ CHAR(5) NOT NULL,
RESP VARCHAR2(10) NOT NULL
);

CREATE TABLE SERVICEV (
NUSERV NUMBER(2,0) PRIMARY KEY,
NOMSERV VARCHAR2(10) NOT NULL,
CHEF NUMBER(4,0) NOT NULL
);

CREATE TABLE TRAVAIL (
NUEMPL NUMBER(4,0) NOT NULL,
NUPROJ NUMBER(3,0) NOT NULL,
DUREE NUMBER(2,0),
CONSTRAINT CLE_TRAVAIL PRIMARY KEY(NUEMPL,NUPROJ),
CONSTRAINT FK_EMPLOYE FOREIGN KEY (NUEMPL) REFERENCES EMPLOYE(NUEMPL),
CONSTRAINT FK_PROJET FOREIGN KEY (NUPROJ) REFERENCES PROJET(NUPROJ)
);

CREATE TABLE CONCERNE (
NUSERV NUMBER(2,0) NOT NULL,
NUPROJ NUMBER(3,0) NOT NULL,
CONSTRAINT CLE_CONCERNE PRIMARY KEY(NUSERV,NUPROJ),
CONSTRAINT FK_SERVICE FOREIGN KEY (NUSERV) REFERENCES SERVICEV(NUSERV),
CONSTRAINT FK_PROJET2 FOREIGN KEY (NUPROJ) REFERENCES PROJET(NUPROJ)
);

CREATE TABLE R (
A NUMBER(3,0),
B NUMBER(3,0),
C NUMBER(3,0)
);

DROP TABLE EMPLOYE;
DROP TABLE PROJET;
DROP TABLE SERVICEV;
DROP TABLE TRAVAIL;
DROP TABLE CONCERNE;
DROP TABLE R;

INSERT INTO EMPLOYE VALUES(20,'MARCEL' ,35,3);
INSERT INTO EMPLOYE VALUES(23,'CLAUDE',20,3);
INSERT INTO EMPLOYE VALUES(37,'MICHELE',35,3);

INSERT INTO R VALUES(1,2,3);
INSERT INTO R VALUES(1,0,1);
INSERT INTO R VALUES(5,1,1);
INSERT INTO R VALUES(5,2,3);

SELECT A,sum(B) from R group by A;
SELECT A, count(*) from R where C = 1 group by A;
select B, count(*) from R where C=3 group by B having count(*) > 1;

SELECT * from basetd.employe;
SELECT * from basetd.projet;
SELECT * FROM basetd.travail;

SELECT distinct nomproj,resp,nomempl from basetd.projet natural JOIN basetd.employe;

