fun main() {
    val jfr = Citoyen("Remm", "Jean-Francois")
    val jfb = Citoyen("Berdjugin", "Jean-Francois")
    val cj = Citoyen("Jacquin", "Christine")
    val ab = Citoyen("Benjilany", "Ali")
    val alb = Citoyen("Lanoix Brauer", "Arnaud")
    println(jfr)
    println(jfb)
    println(cj)
    println(ab)
    println(alb)
    println("$alb est inscrit ? ${alb.estInscrit()}")
    val bureau = BureauDeVote(42,4)
    println(bureau)
    println("election possible ? ${bureau.electionPossible()}")
    bureau.inscrire(jfr)
    bureau.inscrire(jfb)
    println(jfr)
    println(jfb)
    println(bureau)
    println("election possible ? ${bureau.electionPossible()}")
    bureau.designerPresident(jfb)
    println(bureau)
    println("election possible ? ${bureau.electionPossible()}")
    var res = bureau.inscrire(jfr)
    println("reinscription de $jfr ? $res")
    bureau.inscrire(cj)
    bureau.inscrire(ab)
    res = bureau.inscrire(alb)
    println("inscription de $alb ? $res")
    println(bureau)
    //bureau.reorganiserListe()
}